-- LEFT JOIN 사용

-- INS 에서 NAME, DATETIME
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
-- INS가 메인이 되도록 조인
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
-- 매칭되지 못한것만 (나가지 못한 애들만)
WHERE O.ANIMAL_ID IS NULL
-- DATETIME으로 정렬
ORDER BY I.DATETIME